<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.apache.syncope.ext</groupId>
    <artifactId>syncope-ext-javers</artifactId>
    <version>4.1.1-SNAPSHOT</version>
  </parent>

  <name>Apache Syncope Ext: Javers REST API</name>
  <description>Apache Syncope Ext: Javers REST API</description>
  <groupId>org.apache.syncope.ext.javers</groupId>
  <artifactId>syncope-ext-javers-rest-api</artifactId>

  <properties>
    <rootpom.basedir>${basedir}/../../..</rootpom.basedir>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.apache.syncope.common.idrepo</groupId>
      <artifactId>syncope-common-idrepo-rest-api</artifactId>
      <version>${project.version}</version>
    </dependency>
    
    <dependency>
      <groupId>org.apache.syncope.ext.javers</groupId>
      <artifactId>syncope-ext-javers-common-lib</artifactId>      
      <version>${project.version}</version>
    </dependency>    
  </dependencies>

  <build>
    <plugins>
      <!-- Generating javadoc JAR artifact for usage with CXF's WADL generator (for core) -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <inherited>true</inherited>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
    
</project>